apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports: 
        - containerPort: 21
        - containerPort: 31110
        - containerPort: 31111
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'pgrep telegraf && pgrep vsftpd'
          initialDelaySeconds: 30
          periodSeconds: 5 
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: http
    port: 21
    protocol: TCP
    targetPort: 21
  - port: 31110
    name: p1
  - port: 31111
    name: p2