apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        ports: 
        - containerPort: 5050
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - 'pgrep telegraf && pgrep nginx  && pgrep php-fpm7'
          initialDelaySeconds: 30
          periodSeconds: 5 
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - name: http
    port: 5050
    protocol: TCP
    targetPort: 5050